### ISSUE TITLE
.NET Core support on Linux

### ISSUE THREAD

**Issue by discosultan** [discosultan/VulkanCore#2]
Currently VulkanCore works on Linux systems when run under Mono. Running under .NET Core does not work because there is no elegant way to forward Platform Invoke calls from `vulkan-1.dll` to `vulkan.so`.

https://github.com/dotnet/coreclr/issues/930

It shouldn't be too big of an issue at the moment since Xamarin and more popular Linux .NET GUI systems are all still Mono based.

Possible workaround to support .NET Core on Linux would be to duplicate all the Platform Invoke methods (`DllImport`) to include both `vulkan-1.dll` and `vulkan.so` variants and choose appropriate method call at runtime based on current platform. The downside is that it adds a lot of boilerplate to the source and potentially adds a minor performance cost.

**Comment by FacticiusVir** [comment]
There's another .NET Core Vulkan project that uses Kernel32 & Libdl instead of PInvoke, bypassing DLL-mapping: https://github.com/mellinoe/vk/tree/master/src/vk

**Comment by discosultan** [comment]
@FacticiusVir Thanks for pointing this out! I'll look into it.

**Comment by amerkoleci** [comment]
Entry points need to be loaded dynamically not by using PINVOKE seams

**Comment by amerkoleci** [comment]
Same approach will work for Android tho

**Comment by discosultan** [comment]
I've moved the library over from using Platform Invoke to the method pointed by @FacticiusVir (https://github.com/discosultan/VulkanCore/commit/0867c1cfe8fd9724c528e078c47429dd6e4af9a8). Managed to get all the tests passing in Ubuntu on .NET Core, yey 👍

**Comment by discosultan** [comment]
Another potential solution which may allow the usage of `DllImport` in a cross-platform manner: https://github.com/dotnet/coreclr/issues/930#issuecomment-328542896

**Comment by FacticiusVir** [comment]
It's such a horrible workaround, but hey, if they can't get organised about DllMap...
