### ISSUE TITLE
Device-specific Validation Layers not exposed

### ISSUE THREAD

**Issue by WardBenjamin** [discosultan/VulkanCore#25]
#24 reminded me that device-specific enabled validation layer functionality isn't exposed via the DeviceCreateInfo constructor.

From 
```cs 
internal unsafe void ToNative(out DeviceCreateInfo.Native val)
```
```cs
val.EnabledLayerCount = 0;
val.EnabledLayerNames = (IntPtr*) null;
```

Is there a reason for this? It's deprecated, yes, but the specification document still recommends that you enable validation layers at device level as well for compatibility, since it's required by some implementations. Ideally, the solution would be to specify the same validation layers as the main instance rather than having none at all.

Thanks for your work; VulkanCore has been great.

**Comment by discosultan** [comment]
Good point. I think they have been deprecated for quite a long time. Although I find it weird now that I've designed it in a way that there is no option to set it at all. What makes sense would be to hide the deprecated values from the ctor but still make the `EnabledLayerNames` field public and convert to interop form.
