### ISSUE TITLE
SurfaceKhr Constructor Visibility

### ISSUE THREAD

**Issue by WardBenjamin** [discosultan/VulkanCore#30]
One of the main advantages of a library such as GLFW or SDL is that the library can transparently handle the platform-specific code associated with Surface creation, so that you don't need to implement per-platform code C#-side. 

Currently, VulkanCore doesn't publically expose the [`SurfaceKhr(Instance parent, ref AllocationCallbacks? allocator, long handle)`](https://github.com/discosultan/VulkanCore/blob/master/Src/Khr/SurfaceKhr.cs#L104) constructor. This means that even though you can access the Instance handle (via the VulkanHandle superclass) to create the surface via these libraries, you can't represent the Surface as a VulkanCore object without creating an instance via reflection of the `internal` constructor.

The simplest solution would be to just make the constructor public, but there's definitely room for other solutions.

**Comment by discosultan** [comment]
Public constructor sounds reasonable. I guess in case the handle for the surface is obtained elsewhere, it doesn't even make sense to pass `Instance` and `AllocationCallbacks` args to `SurfaceKhr`. Perhaps we should simply add a new public constructor which only accepts a handle.

**Comment by WardBenjamin** [comment]
You need to pass in the Instance and AllocationCallbacks because they're also used in the `vkDestroySurfaceKHR` call - I'll submit a PR for the visibility change shortly.

**Comment by WardBenjamin** [comment]
See #31

**Comment by discosultan** [comment]
Ah okay - I thought the entire lifetime of the surface (including destroying it) was managed externally. The PR is now merged.
