### ISSUE TITLE
Branch: v1.1 Fix DebugUtilsMessengerCreateInfoExt

### ISSUE THREAD

**Issue by jchand99** [discosultan/VulkanCore#39]
The DebugUtilsMessengerCreateInfoExt struct has a variable called MessageSeverity with an incorrect type of DebugUtilsMessageTypesExt. It should be of type DebugUtilsMessageSeveritiesExt.

**Comment by discosultan** [comment]
Fixed by https://github.com/discosultan/VulkanCore/commit/4fe1adf5880b65db533d896e8f2751b83700a090. Apologies for extremely late reply and thanks!
