### ISSUE TITLE
Use vkGetInstanceProcAddr for function pointers not statically exposed

### ISSUE THREAD

**Issue by TYoung86** [discosultan/VulkanCore#8]
Vulkan commands are not necessarily exposed statically on a platform.
Function pointers for all Vulkan commands can be obtained with this command.

https://www.khronos.org/registry/vulkan/specs/1.0/man/html/vkGetInstanceProcAddr.html

This is used already by VulkanCore for some applicable function pointers.

The cases where it is not used (incorrectly) should be carefully identified.

- [ ] <s>vkCreateAndroidSurfaceKHR</s>
- [ ] <s>vkCreateMirSurfaceKHR</s>
- [ ] <s>vkGetPhysicalDeviceMirPresentationSupportKHR</s>
- [ ] vkCreateViSurfaceNN
- [ ] <s>vkCreateWaylandSurfaceKHR</s>
- [ ] <s>vkGetPhysicalDeviceWaylandPresentationSupportKHR</s>
- [ ] <s>vkCreateXlibSurfaceKHR</s>
- [ ] <s>vkGetPhysicalDeviceXlibPresentationSupportKHR</s>
- [ ] <s>vkCreateXcbSurfaceKHR</s>
- [ ] <s>vkGetPhysicalDeviceXcbPresentationSupportKHR</s>
- [ ] vkCreateDebugReportCallbackEXT
- [ ] vkDestroyDebugReportCallbackEXT
- [ ] vkDebugReportMessageEXT
- [ ] vkDebugMarkerSetObjectNameEXT
- [ ] vkDebugMarkerSetObjectTagEXT
- [ ] vkCmdDebugMarkerBeginEXT
- [ ] vkCmdDebugMarkerEndEXT
- [ ] vkCmdDebugMarkerInsertEXT
- [ ] vkGetPhysicalDeviceExternalImageFormatPropertiesNV
- [ ] vkGetMemoryWin32HandleNV
- [ ] vkCmdDrawIndirectCountAMD
- [ ] vkCmdDrawIndexedIndirectCountAMD
- [ ] vkCmdProcessCommandsNVX
- [ ] vkCmdReserveSpaceForCommandsNVX
- [ ] vkCreateIndirectCommandsLayoutNVX
- [ ] vkDestroyIndirectCommandsLayoutNVX
- [ ] vkCreateObjectTableNVX
- [ ] vkDestroyObjectTableNVX
- [ ] vkRegisterObjectsNVX
- [ ] vkUnregisterObjectsNVX
- [ ] vkGetPhysicalDeviceGeneratedCommandsPropertiesNVX
- [ ] vkGetPhysicalDeviceFeatures2KHR
- [ ] vkGetPhysicalDeviceProperties2KHR
- [ ] vkGetPhysicalDeviceFormatProperties2KHR
- [ ] vkGetPhysicalDeviceImageFormatProperties2KHR
- [ ] vkGetPhysicalDeviceQueueFamilyProperties2KHR
- [ ] vkGetPhysicalDeviceMemoryProperties2KHR
- [ ] vkGetPhysicalDeviceSparseImageFormatProperties2KHR
- [ ] vkCmdPushDescriptorSetKHR
- [ ] vkTrimCommandPoolKHR
- [ ] vkGetPhysicalDeviceExternalBufferPropertiesKHX
- [ ] vkGetMemoryWin32HandleKHX
- [ ] vkGetMemoryWin32HandlePropertiesKHX
- [ ] vkGetMemoryFdKHX
- [ ] vkGetMemoryFdPropertiesKHX
- [ ] vkGetPhysicalDeviceExternalSemaphorePropertiesKHX
- [ ] vkGetSemaphoreWin32HandleKHX
- [ ] vkImportSemaphoreWin32HandleKHX
- [ ] vkGetSemaphoreFdKHX
- [ ] vkImportSemaphoreFdKHX
- [ ] vkReleaseDisplayEXT
- [ ] vkAcquireXlibDisplayEXT
- [ ] vkGetRandROutputDisplayEXT
- [ ] vkDisplayPowerControlEXT
- [ ] vkRegisterDeviceEventEXT
- [ ] vkRegisterDisplayEventEXT
- [ ] vkGetSwapchainCounterEXT
- [ ] vkGetPhysicalDeviceSurfaceCapabilities2EXT
- [ ] vkEnumeratePhysicalDeviceGroupsKHX
- [ ] vkGetDeviceGroupPeerMemoryFeaturesKHX
- [ ] vkBindBufferMemory2KHX
- [ ] vkBindImageMemory2KHX
- [ ] vkCmdSetDeviceMaskKHX
- [ ] vkGetDeviceGroupPresentCapabilitiesKHX
- [ ] vkGetDeviceGroupSurfacePresentModesKHX
- [ ] vkAcquireNextImage2KHX
- [ ] vkCmdDispatchBaseKHX
- [ ] vkGetPhysicalDevicePresentRectanglesKHX
- [ ] vkCreateDescriptorUpdateTemplateKHR
- [ ] vkDestroyDescriptorUpdateTemplateKHR
- [ ] vkUpdateDescriptorSetWithTemplateKHR
- [ ] vkCmdPushDescriptorSetWithTemplateKHR
- [ ] vkSetHdrMetadataEXT
- [ ] vkGetSwapchainStatusKHR
- [ ] vkGetRefreshCycleDurationGOOGLE
- [ ] vkGetPastPresentationTimingGOOGLE
- [ ] vkCreateIOSSurfaceMVK
- [ ] vkCreateMacOSSurfaceMVK
- [ ] vkCmdSetViewportWScalingNV
- [ ] vkCmdSetDiscardRectangleEXT
- [ ] vkGetPhysicalDeviceSurfaceCapabilities2KHR
- [ ] vkGetPhysicalDeviceSurfaceFormats2KHR

**Comment by discosultan** [comment]
@TYoung86 Thanks for pointing this out! This may very well be the case as I've only tested core Vulkan commands.

I'm not aware if there is a resource available to find out statically exported commands and if that may also differ per platform / driver (in addition to Vulkan version). One way would be to simply fetch pointers for all the static commands and see if they return a valid pointer. But that wouldn't tell if the static command is missing because the extension is not supported or the command is not statically exported.

**Comment by TYoung86** [comment]
It looks like once vkGetInstanceProcAddr and a Vulkan Instance are obtained, all other function pointers can be obtained through vkGetInstanceProcAddr; it may simply be better to rely on it for first chance linkage.

**Comment by discosultan** [comment]
That might be a good idea!

An important thing to find out is if and how big performance differences are there between command pointers acquired through `vkGetInstanceProcAddr`/`vkGetDeviceProcAddr` vs `VulkanLibrary` (without caching).

Implementation should be relatively trivial:

- Turn static delegates into instance delegates (since available commands differ per `vkInstance`/`vkDevice`)
- Use `Instance.GetProc`/`Device.GetProc` instead of `VulkanLibrary.GetProc`

**Comment by TYoung86** [comment]
Updated the ticket reflecting the missing exports.

What about other platforms?

**Comment by discosultan** [comment]
I've reworked most of the extension commands to use `GetProc` from `Device`/`Instance` (https://github.com/discosultan/VulkanCore/commit/180c60fe66db6c04c6a8cc48ed2187efa4e0f178, https://github.com/discosultan/VulkanCore/commit/c35afa11d1f5902833f998304481a4b1bb010fe5). 

The following commands still use the statically exported variant (other platforms still untested):

- vkGetPhysicalDeviceDisplayPropertiesKHR
- vkGetPhysicalDeviceDisplayPlanePropertiesKHR
- vkGetDisplayPlaneSupportedDisplaysKHR
- vkGetDisplayModePropertiesKHR
- vkCreateDisplayModeKHR
- vkGetDisplayPlaneCapabilitiesKHR
- vkCreateDisplayPlaneSurfaceKHR
- vkCreateSharedSwapchainsKHR
- vkDestroySurfaceKHR
- vkGetPhysicalDeviceSurfaceSupportKHR
- vkGetPhysicalDeviceSurfaceCapabilitiesKHR
- vkGetPhysicalDeviceSurfaceFormatsKHR
- vkGetPhysicalDeviceSurfacePresentModesKHR
- vkCreateSwapchainKHR
- vkDestroySwapchainKHR
- vkGetSwapchainImagesKHR
- vkAcquireNextImageKHR
- vkQueuePresentKHR
- vkCreateWin32SurfaceKHR
- vkGetPhysicalDeviceWin32PresentationSupportKHR
- vkCreateAndroidSurfaceKHR
- vkCreateMirSurfaceKHR
- vkGetPhysicalDeviceMirPresentationSupportKHR
- vkCreateWaylandSurfaceKHR
- vkGetPhysicalDeviceWaylandPresentationSupportKHR
- vkCreateXlibSurfaceKHR
- vkGetPhysicalDeviceXlibPresentationSupportKHR
- vkCreateXcbSurfaceKHR
- vkGetPhysicalDeviceXcbPresentationSupportKHR

**Comment by TYoung86** [comment]
I haven't had much time to work on things, but I'll update the checklist above to exclude these...
Feel free to check the checkboxes on the ones you can confirm are implemented, I'll help out and check them off after looking over things eventually. Is there a way we can create a test from this?

**Comment by discosultan** [comment]
@TYoung86 I don't know of a clever way to automatically test ALL the commands. Maybe by reflecting through all the handle types' methods and invoking them with default values as arguments and asserting that no `NullReferenceException` (in case no handle to Vulkan command was found) or `AccessViolationException` is thrown. Additionally, only those commands should be tested for which extensions are available on given platform.

Ideal would be to manually create a test with valid usage for every command but that is a lot of work. Core API (without extensions) already has quite a good coverage.

**Comment by TYoung86** [comment]
I'm [switching over ](https://github.com/TYoung86/Vulkan.Binder)to an automated binding generation strategy, (maybe?) similar to the vk project...
Going to start working on a test suite next weekend, and maybe somehow generate some automatic coverage tests, going to shoot for 100%...

**Comment by discosultan** [comment]
@TYoung86 Good luck with the generator! It'd be nice to have a high quality bindings generator available.

-----

I'm closing the issue for now. It'd be nice to have coverage on the aforementioned commands but in theory they should be working correctly now.
